#! /bin/bash
# @author:haloo#
#@func:pre-commit#
## cp ./checkstyle/pre-commit  ./.git/hooks/


# print 避免NPE是程序员的基本修养
# print 开始style checking

wd=`pwd`
print "当前工作目录：$wd"

# check-style版本号
check_style_version="config/checkstyle/checkstyle-10.3.1-all.jar"
check_style_xml_name="config/checkstyle/checkstyle.xml"
check_jar_path="$wd/$check_style_version"
check_xml_path="$wd/$check_style_xml_name"

## 清空temp文件

rm -f temp

is_err=0
errorCount=0
warnCount=0

## 查找add到git 缓冲区中，以.java后缀的文件
for file in `git status --porcelain | sed s/^...// | grep '\.java$'`; do
    path="$wd/$file"
    print "检查文件: $path"
    re=`java -jar $check_jar_path -c $check_xml_path $path >> temp`
    warn=`cat temp | grep  "WARN"`

    if [[ $warn = *"WARN"* ]];then
        echo "{$warn}"
        ((warnCount++))
        is_err=1
     fi

     err=`cat temp | grep  "ERROR"`
     if [[ $err = *"ERROR"* ]];then
         echo "${err}"
         ((errorCount++))
         is_err=1
      fi
done


print "检查完成,祝你好运"

rm -f temp

if [ $is_err -ne  0 ];then
    print "出现了 $errorCount 个error"
    print "出现了 $warnCount 个warn"
    print "请先符合style才能提交"
    exit 1
fi
print "No Bug ,It is Good!!"
exit 0
